# Generated by Django 5.0.2 on 2024-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodunityhubapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatorregis',
            name='donatorid',
        ),
        migrations.AddField(
            model_name='donatorregis',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
